name: Setup
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node 12
      uses: actions/setup-node@v4
      with:
        node-version: 12.x
        cache: 'npm'
    - name: Install dependencies
      shell: bash
      run: npm i