services: 
  mongodb:
    container_name: mongodb-container
    image: mongo:3
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-prod
    image: node:12
    working_dir: /usr/src/
    build: .
    restart: always
    command: bash -c "npm install --only=prod && npm run start"
    volumes:
      - ./dist/:/usr/src/dist/
      - ./package.json:/usr/src/package.json
    ports:
      - "5050:5050"
    links:
      - mongodb
    
