services: 
  mongodb:
    container_name: mongodb-container
    image: mongo:3
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    image: clean-ts-api
    build: .
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/dist
      - ./package.json:/usr/src/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongodb
    
