name: Checks
on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 12.x

      - name: Lint
        run: npm run lint:all

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Setup
#        uses: ./.github/actions/setup
#        with:
#          node-version: 12.x

      - name: Setup Node 12.x
        uses: actions/setup-node@v4
        with:
          node-version: 12.x

      - run: npm i

      - name: Test CI
        run: npm run test:ci