name: Checks
on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node 12
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
          cache: 'npm'
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules-${{ hashFiles('package-lock.json') }}
          path: node_modules
      - name: Set var if node_modules exists
        if: failure()
        run: echo "NODE_MODULES_EXISTS=true" >> $GITHUB_ENV

      - name: Install dependencies
        if: ${{ env.NODE_MODULES_EXISTS }} != 'true'
        run: npm ci
      - name: Show folder
        run: ls -la
      - name: Upload node_modules
        if: ${{ env.NODE_MODULES_EXISTS }} != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: node_modules-${{ hashFiles('./package-lock.json') }}
          path: node_modules



  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node 12
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
          cache: 'npm'
      - name: Download node_modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules-${{ hashFiles('package-lock.json') }}
          path: node_modules
      - name: Show folder
        run: ls -la
      - name: Lint
        run: npm run lint:all

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup
#        uses: ./.github/actions/setup
#      - name: Test CI
#        run: npm run test:ci