name: Checks
on:
  push:
    branches: [ master ]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      node-version: 12.x

  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Setup
        uses: ./.github/workflows/setup.yml
        with:
          node-version: 12.x
      - name: Lint
        run: npm run lint:all

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/setup
        with:
          node-version: 12.x
      - name: Test CI
        run: npm run test:ci