name: Checks
on:
  push:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 12
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
          cache: 'npm'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          key: node_modules-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install dependencies
        if: ${{ hashFiles('node_modules') == '' }}
        run: npm ci

      - name: Show folder
        run: ls -la



  lint:
    runs-on: ubuntu-latest
    needs: [setup]
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 12
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
          cache: 'npm'

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          key: node_modules-${{ hashFiles('package-lock.json') }}
          path: node_modules

      - name: Install dependencies
        if: ${{ hashFiles('node_modules') == '' }}
        run: npm ci

      - name: Show folder
        run: ls -la

      - name: Lint
        run: npm run lint:all

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Setup
#        uses: ./.github/actions/setup
#      - name: Test CI
#        run: npm run test:ci